# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - npm install
  - npm run build
  - rm -rf public
  - cp build/index.html build/404.html
  - mv build public
